version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - db-net

  flyway-animal:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:5432/animal -user=postgres -password=postgres -connectRetries=10 migrate
    volumes:
      - ./flyway/animal/sql:/flyway/sql
    depends_on:
      - postgres
    networks:
      - db-net

  flyway-birds:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:5432/birds -user=postgres -password=postgres -connectRetries=10 migrate
    volumes:
      - ./flyway/birds/sql:/flyway/sql
    depends_on:
      - postgres
    networks:
      - db-net

volumes:
  postgres_data:

networks:
  db-net:
