version: '3.1'

services:
  flyway-animal:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:5432/animal -user=postgres -password=postgres -connectRetries=10 migrate
    volumes:
      - ./flyway/animal/sql:/flyway/sql
    depends_on:
      - postgres
    networks:
      - db-net

  flyway-birds:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:5432/birds -user=postgres -password=postgres -connectRetries=10 migrate
    volumes:
      - ./flyway/birds/sql:/flyway/sql
    depends_on:
      - postgres
    networks:
      - db-net

networks:
  db-net:
    external: true
